# Dependency Review configuration
# https://github.com/actions/dependency-review-action#configuration-options
#
# actions/checkout@v6 and other GitHub-owned actions are MIT-licensed.
# GitHub's dependency review database does not always carry license metadata
# for major-version floating tags (v6.*.*), causing false-positive "Unknown License"
# warnings. The packages below are explicitly allowed.

allow-dependencies-licenses:
  - dependency-name: "actions/checkout"
    versions:
      - "*"
  - dependency-name: "actions/setup-python"
    versions:
      - "*"
  - dependency-name: "actions/upload-artifact"
    versions:
      - "*"
  - dependency-name: "actions/download-artifact"
    versions:
      - "*"
  - dependency-name: "actions/cache"
    versions:
      - "*"
